paths:
  raw: "data/raw"
  bronze: "data/bronze"
  silver: "data/silver"
  gold: "data/gold"
  logs: "logs"

spark:
  app_name: "YELP DATA PIPELINE"
  master: "local[*]"
  driver_memory: "8g"
  executor_memory: "4g"
  shuffle_partitions: "64"

datasets:
  - business
  - review
  - user
  - checkin
  - tip

